import { deepFreeze, validateBaseManifest } from "@unej-cms/sdk-core";
import {
  blockNamespace,
  CORE_BLOCK_NAMESPACE,
  type BlockDefinition,
  type PropertySchema,
} from "@unej-cms/sdk-ui";
import type { ThemeManifest } from "./manifest.js";
import type { LayoutDefinition } from "./layout.js";
import type { RegionDefinition } from "./region.js";
import type { MenuLocationDefinition } from "./menu-location.js";
import type { CmsStyle } from "./style.js";
import type { ThemeTokens } from "./tokens.js";
import type { ThemeTemplateDefinition } from "./template.js";

/**
 * Everything a theme declares, up front (Declarative Registration). A theme
 * has no lifecycle and never touches a database — it may only register
 * layouts, regions, menu locations, settings, and assets
 * (docs/cms_sdk.md §15).
 */
export interface CmsTheme<TRender = unknown> {
  readonly manifest: ThemeManifest;
  readonly layouts: readonly LayoutDefinition<TRender>[];
  readonly regions?: readonly RegionDefinition[];
  readonly menuLocations?: readonly MenuLocationDefinition[];
  /** Configurable options (colors, toggles, ...) surfaced in the Dashboard's theme settings panel. */
  readonly settings?: PropertySchema;
  /** Separate stylesheet/script assets, emitted as their own files (asset/style/{css,js}/*). */
  readonly styles?: readonly CmsStyle[];
  /** Fixed design decisions (colors/typography/radius/layout/spacing), flattened into CSS custom properties by the Builder Runtime. Distinct from `settings`, which are admin-editable per site. */
  readonly tokens?: ThemeTokens;
  /** Named page templates editors can pick from, each mapping to one of `layouts[].id`. */
  readonly templates?: readonly ThemeTemplateDefinition[];
  /**
   * Blocks this theme contributes to the Page Builder, on top of the CMS's
   * own `core.*` catalog — the theme's signature sections (a video hero, a
   * mega menu) that only make sense while it is the active theme.
   *
   * Declaring them here is what keeps the Page Builder generic: it reads
   * every available block from the registry rather than hardcoding one
   * theme's components, so a new theme ships new blocks without touching
   * builder code. Each should set `fallback` to a `core.*` block so pages
   * authored with it still render after a theme switch.
   */
  readonly blocks?: readonly BlockDefinition[];
  /**
   * How this theme renders each block type, keyed by block id
   * (docs/theme_aware_prd.md §17) — `core.hero`, `faculty.video-hero`, ...
   *
   * `TRender` is the same opaque representation the theme's layouts use (raw
   * `.svelte` source text for this CMS's Svelte themes), so a block is
   * rendered by the theme's own component with the theme's own markup and
   * classes. This is the half that makes a page authored once look native
   * under whichever theme is active: content lives in the page, presentation
   * lives here.
   *
   * A theme need not cover every block — the Builder Runtime falls back to
   * the block's declared `fallback` type, and skips it entirely if that has
   * no renderer either, rather than emitting a half-styled section.
   */
  readonly blockRenderers?: Readonly<Record<string, TRender>>;
  /**
   * The homepage this theme starts a site with, as Page Builder blocks.
   *
   * Applying a theme materialises these into the site's real homepage Page
   * (fresh block ids are generated by the CMS), so the beranda an editor sees
   * matches the theme — and, unlike the theme's hardcoded `home` layout, every
   * part of it is editable in the builder.
   *
   * Only block types this theme actually renders belong here; anything else
   * would be skipped at render time and read as a missing section.
   */
  readonly defaultHomepage?: readonly ThemeHomepageBlock[];
}

/** One block in a theme's starter homepage. Ids are assigned by the CMS, not the theme. */
export interface ThemeHomepageBlock {
  readonly type: string;
  readonly props: Readonly<Record<string, unknown>>;
}

export class ThemeDefinitionError extends Error {
  constructor(
    themeId: string,
    public readonly issues: readonly { path: string; message: string }[],
  ) {
    super(
      `Invalid theme definition for "${themeId}":\n` +
        issues.map((issue) => `  - ${issue.path}: ${issue.message}`).join("\n"),
    );
    this.name = "ThemeDefinitionError";
  }
}

/**
 * The only entry point a theme author calls directly. Validates the
 * manifest eagerly and freezes the definition so it can't be mutated after
 * the fact (mirrors `definePlugin` in `@unej-cms/sdk-plugin`).
 */
export function defineTheme<TRender = unknown>(
  theme: CmsTheme<TRender>,
): CmsTheme<TRender> {
  const issues = validateBaseManifest(theme.manifest);
  if (theme.layouts.length === 0) {
    issues.push({ path: "layouts", message: "a theme must declare at least one layout" });
  }
  const layoutIds = new Set(theme.layouts.map((layout) => layout.id));
  for (const template of theme.templates ?? []) {
    if (!layoutIds.has(template.layout)) {
      issues.push({
        path: `templates.${template.id}.layout`,
        message: `references unknown layout "${template.layout}"`,
      });
    }
  }

  const seenBlockIds = new Set<string>();
  for (const block of theme.blocks ?? []) {
    const id = String(block.id);
    if (seenBlockIds.has(id)) {
      issues.push({ path: `blocks.${id}`, message: "declared more than once" });
    }
    seenBlockIds.add(id);

    // A theme claiming a `core.*` id would shadow the block every other theme
    // relies on, silently changing what stored content means after a theme
    // switch — the one thing block ids exist to prevent.
    if (blockNamespace(id) === CORE_BLOCK_NAMESPACE) {
      issues.push({
        path: `blocks.${id}`,
        message: `"${CORE_BLOCK_NAMESPACE}." is reserved for CMS core blocks; use the theme's own namespace`,
      });
    }
    if (!blockNamespace(id)) {
      issues.push({
        path: `blocks.${id}`,
        message: 'must be namespaced as "<theme>.<block>", e.g. "faculty.video-hero"',
      });
    }
    if (block.fallback === id) {
      issues.push({ path: `blocks.${id}.fallback`, message: "cannot fall back to itself" });
    }
  }

  if (issues.length > 0) {
    throw new ThemeDefinitionError(theme.manifest.id || "<unknown>", issues);
  }
  return deepFreeze(theme);
}
